---
data_type:
    select: [second,index]
    electrography: [volt,millivolt,microvolt]
    interval: [second,millisecond,index]
    beating_rate: [bpm]
    peak: [second,millisecond,index]

integration_level:
    - select
    - electrocardiogram
    - electrogram
    - action potential
mammal:
    - select
    - dog
    - mouse
    - rabbit
    - human
    - custom
units:
    second: [s,sec,second]
    millisecond: [ms,msec,millisecond]
    volt: [v,volt]
    millivolt: [mv,mvolt,millivolt]
    microvolt: [uv,mkvolt,microvolt,mikrovolt]
    index: [index,ind,i]
    bpm: [bpm]
alarm:
    msg_1: The sampling frequency Fs was re-computed to match the time axis that was entered
    msg_2: The set of channels selected do not match
    msg_3: The sampling frequency entered Fs does not match with the selected time channel